//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBox.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Releases = new HashSet<Release>();
        }
    
        public int ArtistID { get; set; }
        public string ArtistName { get; set; }
        public string ArtistDescription { get; set; }
        public string MusicBrainzID { get; set; }
    
        public virtual ICollection<Release> Releases { get; set; }
    }
}
