//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DataMigration.SqlDataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NorthwindContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NorthwindContext object using the connection string found in the 'NorthwindContext' section of the application configuration file.
        /// </summary>
        public NorthwindContext() : base("name=NorthwindContext", "NorthwindContext")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NorthwindContext object.
        /// </summary>
        public NorthwindContext(string connectionString) : base(connectionString, "NorthwindContext")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NorthwindContext object.
        /// </summary>
        public NorthwindContext(EntityConnection connection) : base(connection, "NorthwindContext")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shipper> Shippers
        {
            get
            {
                if ((_Shippers == null))
                {
                    _Shippers = base.CreateObjectSet<Shipper>("Shippers");
                }
                return _Shippers;
            }
        }
        private ObjectSet<Shipper> _Shippers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shippers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShippers(Shipper shipper)
        {
            base.AddObject("Shippers", shipper);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Shipper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shipper : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shipper object.
        /// </summary>
        /// <param name="shipper_ID">Initial value of the Shipper_ID property.</param>
        /// <param name="company_Name">Initial value of the Company_Name property.</param>
        public static Shipper CreateShipper(global::System.Int32 shipper_ID, global::System.String company_Name)
        {
            Shipper shipper = new Shipper();
            shipper.Shipper_ID = shipper_ID;
            shipper.Company_Name = company_Name;
            return shipper;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Shipper_ID
        {
            get
            {
                return _Shipper_ID;
            }
            set
            {
                if (_Shipper_ID != value)
                {
                    OnShipper_IDChanging(value);
                    ReportPropertyChanging("Shipper_ID");
                    _Shipper_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Shipper_ID");
                    OnShipper_IDChanged();
                }
            }
        }
        private global::System.Int32 _Shipper_ID;
        partial void OnShipper_IDChanging(global::System.Int32 value);
        partial void OnShipper_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Company_Name
        {
            get
            {
                return _Company_Name;
            }
            set
            {
                OnCompany_NameChanging(value);
                ReportPropertyChanging("Company_Name");
                _Company_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Company_Name");
                OnCompany_NameChanged();
            }
        }
        private global::System.String _Company_Name;
        partial void OnCompany_NameChanging(global::System.String value);
        partial void OnCompany_NameChanged();

        #endregion

    
    }

    #endregion

    
}
